import { Node } from "reactflow";

export const initNodes: Node[] = [
  {
    id: "layer-1",
    data: { label: "Cuatrimestre 1" },
    position: { x: 0, y: 0 },
    style: {
      backgroundColor: "rgb(172,204,234)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "0",
    type: "custom",
    data: {
      bg_color: "bg-[#fef445]",
      codigo: "N1",
      anio: 1,
      ciclo: "Básico",
      cuatrimestre: 1,
      condicion: "carrera",
      materia: "Análisis 1",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: null,
      ch_presencial: 128.0,
      ch_distancia: 0.0,
      ch_total: 128.0,
      descripcion:
        "Números reales. Propiedades. Intervalos en R. Módulo. Concepto de función. Dominio. Gráficas. Inyectividad y suryectividad. Función inversa. Funciones polinomiales, racionales, exponenciales y logarítmicas. Límites de funciones y Continuidad. Discontinuidades: clasificación. Cálculo diferencial. Reglas de derivación. Fórmula de Taylor. Aplicaciones de las derivadas. Intervalos de monotonía. Extremos locales. Extremos absolutos. Concavidad. Puntos de inflexión. Análisis de funciones. Gráficas aproximadas. Integral. Primitivas. Fórmula de Barrow. Cálculo integral y sus aplicaciones. Integrales impropias. Introducción a las ecuaciones diferenciales ordinarias. Métodos elementales de integración. Ecuaciones con variables separables y lineales de primer y de segundo orden.",
    },
    position: {
      x: 200,
      y: 100,
    },
    parentNode: "layer-1",
  },
  {
    id: "1",
    type: "custom",
    data: {
      bg_color: "bg-[#b8df86]",
      codigo: "CD01",
      anio: 1,
      ciclo: "Básico",
      cuatrimestre: 1,
      condicion: "carrera",
      materia: "Introducción a la Ciencia de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "Introducción práctica al análisis de datos. La relación entre los datos y los problemas prácticos. Formulación de preguntas relevantes y pasos de resolución de un problema realista de ciencia de datos. Presentación en casos reales. Obtención y carga de datos. Formato de almacenamiento de datos (csv, tsv, ascii). Encabezados. Formato de los datos (numérico, string, fechas y otros). Técnicas y herramientas de exploración y visualización de los datos. Evaluación y corrección de datos. Datos faltantes, datos incorrectos. Análisis exploratorio de los datos. Selección, descubrimiento y dise\u00f1o de features relevantes para la resolución de un problema dado.\n\nTécnicas descriptivas de los datos. Muestras. Valor medio, desvío estándar. Estadísticos. Estimadores. Concepto de correlación y covarianza. Coeficiente de correlación. Coeficiente de Pearson. Coeficiente de Spearman. Outliers. Sensibilidad de distintos estimadores a los outliers.\n\nModelado de los datos. Modelos estadísticos básicos. Parámetros de los modelos. Regresión lineal simple. Interpretación. Nociones de ajuste por cuadrados mínimos. Estimadores de los parámetros del modelo lineal. Supuestos del modelo lineal. Diagnósticos del ajuste. Evaluación del modelo. Introducción básica a test estadísticos, residuos, QQplots. Residuos. Leverage. Outliers. Extensión de los modelos. Modelos aditivos. Regresión lineal múltiple.",
    },
    position: {
      x: 700,
      y: 100,
    },
    parentNode: "layer-1",
  },
  {
    id: "2",
    type: "custom",
    data: {
      bg_color: "bg-[#e6a6bf]",
      codigo: "CD02",
      anio: 1,
      ciclo: "Básico",
      cuatrimestre: 1,
      condicion: "carrera",
      materia: "Programación 1",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "Introducción al pensamiento algorítmico. Presentación del lenguaje de programación Python. Diferentes entornos de programación (consola, IDE, notebooks). Sintaxis del lenguaje. Tipos de datos básicos. Funciones y documentación. Estructuras de control básicas: condicionales (if; while), iteraciones (for), comprensión de listas. Estructuras de datos: diccionarios, listas, tuplas, vectores, matrices y árboles. Módulos y paquetes. Concepto de namespace. Introducción a la programación orientada a objetos. Conceptos básicos, métodos, atributos, herencia. Estructuras de lectura y escritura de datos. Visualización de datos. Testeo y debuggeo de los programas. Manejo de excepciones. Control de flujos. Introducción a paquetes de cálculo (numpy) y visualización (matplotlib). Elementos de cálculo numérico para análisis matemático.",
    },
    position: {
      x: 1200,
      y: 100,
    },
    parentNode: "layer-1",
  },
  {
    id: "layer-2",
    data: { label: "Cuatrimestre 2" },
    position: { x: 0, y: 400 },
    style: {
      backgroundColor: "rgb(172,204,234)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "3",
    type: "custom",
    data: {
      bg_color: "bg-[#fac710]",
      codigo: "N10",
      anio: 1,
      ciclo: "Básico",
      cuatrimestre: 2,
      condicion: "carrera",
      materia: "Análisis 2",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "N1",
      ch_presencial: 128.0,
      ch_distancia: 0.0,
      ch_total: 128.0,
      descripcion:
        "Funciones vectoriales reales. Límites y continuidad. Cálculo diferencial vectorial. Regla de la cadena. Funciones implícitas. Curvas y superficies parametrizadas.  Fórmula de Taylor vectorial. Plano tangente. Problemas de máximos y mínimos. Multiplicadores de Lagrange. Campos escalares y vectoriales. Potencial. Campo tangente y normal. Formas diferenciales exactas. Análisis geométrico de ecuaciones diferenciales. Cambio de coordenadas. Coordenadas polares, esféricas y cilíndricas. Integrales múltiples. Integrales paramétricas, curvilíneas y de superficie. Aplicaciones geométricas. Operadores gradiente, divergencia, rotor y laplaciano.",
    },
    position: {
      x: 600,
      y: 100,
    },
    parentNode: "layer-2",
  },
  {
    id: "4",
    type: "custom",
    data: {
      bg_color: "bg-[#cee741]",
      codigo: "CD03",
      anio: 1,
      ciclo: "Básico",
      cuatrimestre: 2,
      condicion: "carrera",
      materia: "Matemática Discreta",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "N1",
      ch_presencial: 96.0,
      ch_distancia: 32.0,
      ch_total: 128.0,
      descripcion:
        "Introducción a la Teoría de Números, Lógica proporcional clásica y de Predicados de primer orden. Combinatoria. Conjuntos, relaciones y funciones. Relaciones de recurrencia. Algebra de Boole. Teoría de Grafos- Arboles. Sistemas y códigos de numeración. Polinomios. Geometría en el plano y el espacio. Vectores. Producto escalar. Magnitud, distancia y ángulo. Rectas y planos.  Paralelismo y perpendicularidad. Matrices. Operaciones aritméticas matriciales. Transposición. Matriz inversa. Sistemas de ecuaciones lineales. Eliminación gaussiana. Determinulltes. Espacios vectoriales R^n. Sub-espacios. Generadores. Independencia lineal. Bases y dimensión. Intersección, suma y suma directa de sub-espacios. Espacios vectoriales generales. Transformaciones lineales. Producto interno. Ortogonalidad. Bases. Matrices asociadas a una transformación lineal. Autovalores y autovectores. Diagonalización de matrices.",
    },
    position: {
      x: 250,
      y: 100,
    },
    parentNode: "layer-2",
  },
  {
    id: "5",
    type: "custom",
    data: {
      bg_color: "bg-[#75bdfd]",
      codigo: "CD04",
      anio: 1,
      ciclo: "Básico",
      cuatrimestre: 2,
      condicion: "carrera",
      materia: "Introducción al Aprendizaje Automático",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "N1|CD01|CD02",
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "Funcionamiento de los algoritmos de aprendizaje automático. Validez, aplicabilidad, y limitaciones. Conjunto de datos de entrenamiento, validación y testeo. Repaso de regresión lineal. Funciones de error. Sobreajuste. Regularización. Regresión ridge y lasso. Aplicación de algoritmos de aprendizaje automático: regresión y clasificación lineal; discriminullte linear de Fischer; perceptrón; support vector machine; árboles de decisión; naive Bayes.",
    },
    position: {
      x: 950,
      y: 100,
    },
    parentNode: "layer-2",
  },
  {
    id: "layer-3",
    data: { label: "Cuatrimestre 3" },
    position: { x: 0, y: 800 },
    style: {
      backgroundColor: "rgb(126,171,215)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "6",
    type: "custom",
    data: {
      bg_color: "bg-[#0ca789]",
      codigo: "CD05",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 3,
      condicion: "carrera",
      materia: "Infraestructura para Ciencia de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD02",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        'Funcionamiento de una computadora. Unidad de procesamiento central. Memoria RAM. Redes. Tiempo de latencia. Recursos compartidos. Clusters de cálculo. Cálculo usando Unidades de procesamiento de gráficos (GPU). Nociones de escala y capacidades. Conceptos básicos de "cloud computing". Diferencias y ventajas con respecto a las infraestructuras tradicionales. Almacenamiento definido por software. Soluciones de redes definidas por software. Sistemas operativos para servidores. Virtualización. Servicios de red. Servicios de directorio (Active Directory, OpenLDAP)',
    },
    position: {
      x: 1000,
      y: 100,
    },
    parentNode: "layer-3",
  },
  {
    id: "7",
    type: "custom",
    data: {
      bg_color: "bg-[#8cd5be]",
      codigo: "TPI07",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 3,
      condicion: "carrera",
      materia: "Algoritmos I",
      formato_didactico: "Asignatura",
      ch_semanal: 10.0,
      ch_cuatrimestral: 160.0,
      creditos: 10.0,
      correlativas: "N1",
      ch_presencial: 160.0,
      ch_distancia: 0.0,
      ch_total: 160.0,
      descripcion:
        "Especificación e implementación de programas. Corrección de programas. Tipos de datos.  Tipos abstractos. Tratamiento de secuencias. Archivos secuenciales.",
    },
    position: {
      x: 200,
      y: 100,
    },
    parentNode: "layer-3",
  },
  {
    id: "8",
    type: "custom",
    data: {
      bg_color: "bg-[#bbb2a2]",
      codigo: "CB34",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 3,
      condicion: "carrera",
      materia: "Probabilidad y Estadística",
      formato_didactico: "Asignatura",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: 64.0,
      ch_distancia: 0.0,
      ch_total: 64.0,
      descripcion:
        "Experimentos aleatorios. Frecuencias relativas. Modelo de Laplace.  Probabilidad. Independencia y probabilidad condicional. Teorema de Bayes. Cálculo de probabilidades. Variables aleatorias. Funciones de densidad y de probabilidad. Funciones de distribución.  Principales distribuciones discretas y continuas. Variables aleatorias vectoriales.  Distribuciones conjuntas y marginales.  Momentos de primer y segundo orden. Ley de Grandes Números, Teorema Central del Límite. Correlación. Nociones de procesos estocásticos. Función de autocorrelación. Procesos estacionarios. Regresión lineal. Nociones de estadística descriptiva y paramétrica. Test de hipótesis.",
    },
    position: {
      x: 600,
      y: 100,
    },
    parentNode: "layer-3",
  },
  {
    id: "layer-4",
    data: { label: "Cuatrimestre 4" },
    position: { x: 0, y: 1200 },
    style: {
      backgroundColor: "rgb(126,171,215)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "9",
    type: "custom",
    data: {
      bg_color: "bg-[#ecdbbc]",
      codigo: "CD06",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 4,
      condicion: "carrera",
      materia: "Estadística e Inferencia I",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CB34|CD03",
      ch_presencial: 0.0,
      ch_distancia: 128.0,
      ch_total: 128.0,
      descripcion:
        "Conceptos teóricos. Estimación Puntual. Estadísticos suficientes y completos. Estimadores de momentos y de Máxima Verosimilitud. Regiones de confianza.\n\nDistribuciones multivariadas. Normal multivariada. Wishart\n\nRegresión lineal simple y múltiple. Modelos paramétricos lineales. Regresión paso a paso (stepwise regression). Regresión lineal multivariada. Modelos lineales generalizados.\n\nTeoría de la probabilidad como una extensión de la lógica. Razonamiento en presencia de incertidumbre. Lógica bayesiana. Teorema de Bayes. Bayes como un modelo de aprendizaje. Elementos de estadística. Verosimilitud. Priors. Posteriors. Inferencia bayesiana. Modelos con un solo parámetro. Resultados analíticos. Priors conjugados. Familia exponencial. Testeo A/B bayesiano. Visión bayesiana de la regresión con modelos lineales. Construcción de modelos multi-paramétricos. Modelos de mixturas finitas. Mixturas gaussianas. Responsabilidades. El algoritmo esperanza-maximización (EM). Generalización a los modelos de variables latentes. Detección de anomalías. Validación estadística de los modelos. Distribución predictiva posterior. Validación cruzada. Comparación de modelos bayesiana. Consideración de la complejidad de los modelos. Nociones de teoría de la decisión. Modelos gráficos.",
    },
    position: {
      x: 600,
      y: 100,
    },
    parentNode: "layer-4",
  },
  {
    id: "10",
    type: "custom",
    data: {
      bg_color: "bg-[#e35295]",
      codigo: "TPI10",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 4,
      condicion: "carrera",
      materia: "Algoritmos II",
      formato_didactico: "Asignatura",
      ch_semanal: 9.0,
      ch_cuatrimestral: 144.0,
      creditos: 9.0,
      correlativas: "N10|CD03|TPI07",
      ch_presencial: 144.0,
      ch_distancia: 0.0,
      ch_total: 144.0,
      descripcion:
        "Recursión. Tipos de datos abstractos pila, cola, diccionario, árbol, grafo, etc. Metodologías de especificación formal. Lenguajes de especificación formal. Implementaciones.",
    },
    position: {
      x: 100,
      y: 100,
    },
    parentNode: "layer-4",
  },
  {
    id: "11",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: null,
      anio: 2,
      ciclo: "General",
      cuatrimestre: 4,
      condicion: "carrera",
      materia: "Electiva 1",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: null,
      ch_presencial: 0.0,
      ch_distancia: 64.0,
      ch_total: 64.0,
      descripcion: null,
    },
    position: {
      x: 1000,
      y: 100,
    },
    parentNode: "layer-4",
  },
  {
    id: "layer-5",
    data: { label: "Cuatrimestre 5" },
    position: { x: 0, y: 1600 },
    style: {
      backgroundColor: "rgb(42,78,111)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "12",
    type: "custom",
    data: {
      bg_color: "bg-[#999abb]",
      codigo: "CD07",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 5,
      condicion: "carrera",
      materia: "Estadística e Inferencia II",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD06",
      ch_presencial: 0.0,
      ch_distancia: 128.0,
      ch_total: 128.0,
      descripcion:
        "Revisión de la regresión con modelos lineales bayesiana.  Modelos generativos. Modelos de variables latentes. Responsabilidades. Generalización del algoritmo esperanza-maximización (EM). Modelos no paramétricos. Estimación de densidades. Métodos de kernel. K-means. Procesos gaussianos. Procesos de Dirichlet. Modelos jerárquicos bayesianos.",
    },
    position: {
      x: 50,
      y: 100,
    },
    parentNode: "layer-5",
  },
  {
    id: "13",
    type: "custom",
    data: {
      bg_color: "bg-[#f48e3a]",
      codigo: "CD08",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 5,
      condicion: "carrera",
      materia: "Programación 2",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD02|TPI10",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        "Análisis de rendimiento de software (perfilaje). Manejo de aserciones. Utilización avanzada de las clases en python. Herencia múltiple. Variables privadas. Iteradores y generadores. Decoradores. Uso y funcionalidad de los decoradores. Ambientes virtuales. Paquetes de python para la ciencia de datos: pandas, seaborn. Aplicaciones. Utilización de código C, C++, y Fortran desde python.\n\nAmbientes integrales de desarrollo (IDE). Nociones vinculadas con los sistemas de control de versión. Introducción al lenguaje de análisis estadístico R.",
    },
    position: {
      x: 1300,
      y: 100,
    },
    parentNode: "layer-5",
  },
  {
    id: "14",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: null,
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 5,
      condicion: "carrera",
      materia: "Electiva 2",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 96.0,
      ch_distancia: 0.0,
      ch_total: 96.0,
      descripcion: null,
    },
    position: {
      x: 700,
      y: 100,
    },
    parentNode: "layer-5",
  },
  {
    id: "layer-6",
    data: { label: "Cuatrimestre 6" },
    position: { x: 0, y: 2000 },
    style: {
      backgroundColor: "rgb(42,78,111)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "15",
    type: "custom",
    data: {
      bg_color: "bg-[#8fd14f]",
      codigo: "CD09",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 6,
      condicion: "carrera",
      materia: "Ciencia de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD07|TPI10",
      ch_presencial: 32.0,
      ch_distancia: 96.0,
      ch_total: 128.0,
      descripcion:
        "La materia se propone presentar una serie de técnicas de cálculo, preparación de datos y visualización, necesarias para llevar adelante análisis de datos en situaciones de la vida real.\n\nTécnicas de muestreo. Muestreo simple con y sin reposición. Muestreo por rechazo. Muestreo de importancia. Importance-sampling-resampling. Gibbs sampling. Markov Chain Monte Carlo. Metropolis Hastings. Muestreo con ensambles.\n\nExtracción de features y reducción de la dimensionalidad. Variables latentes continuas. Análisis en componentes principales (PCA). PCA probabilístico. PCA bayesiano. PCA con núcleos (kernel PCA). Modelos con variables latentes no lineales. Análisis de componentes independientes.\n\nInferencia aproximada. Métodos variacionales bayesianos. Cálculo Bayesiano Aproximado (ABC). Nociones del lenguaje de programación estadístico R y de la plataforma Stan.\n\nVisualización. Acercamientos modernos a la visualización de datos. Biplots, etc.",
    },
    position: {
      x: 100,
      y: 100,
    },
    parentNode: "layer-6",
  },
  {
    id: "16",
    type: "custom",
    data: {
      bg_color: "bg-[#ffffff]",
      codigo: "TPI14",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 6,
      condicion: "carrera",
      materia: "Bases de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "TPI10",
      ch_presencial: 128.0,
      ch_distancia: 0.0,
      ch_total: 128.0,
      descripcion:
        "Funciones de los sistemas de Base de Datos. Modelos de datos. Lenguajes de consulta. Dise\u00f1o de Base de Datos. Estructuras físicas y lógicas de datos. Optimización de consultas. Transacciones. Concurrencia y recuperación. Implementaciones.",
    },
    position: {
      x: 500,
      y: 100,
    },
    parentNode: "layer-6",
  },
  {
    id: "17",
    type: "custom",
    data: {
      bg_color: "bg-[#771333]",
      codigo: "CD10",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 6,
      condicion: "carrera",
      materia: "Ingeniería de Software",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD08",
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "El proceso de software. Ciclos de vida del software. Prácticas DevOps de desarrollo (Dev) y operaciones (Ops). Prácticas ágiles. Ingeniería de requerimientos. Arquitectura y dise\u00f1o. Patrones. Conceptos de arquitecturas orientadas a servicios. Reingeniería de software. Calidad de software: del producto y del proceso. Dise\u00f1o centrado en el usuario. Administración y control de proyectos. Nociones de auditoría y peritaje. Teoría general de sistemas. Sistemas de información. Privacidad integridad y seguridad en sistemas de información. Nociones de sistemas colaborativos. Documentación. Responsabilidad y ética profesional. Computación y sociedad. Propiedad intelectual, licenciamiento de software y contratos informáticos. Aspectos legales.\n\nNetDevOps, Redes basadas en la intención, Redes basadas en la experiencia. Redes definidas por software. Redes autoconfigurables.",
    },
    position: {
      x: 900,
      y: 100,
    },
    parentNode: "layer-6",
  },
  {
    id: "layer-7",
    data: { label: "Cuatrimestre 7" },
    position: { x: 0, y: 2400 },
    style: {
      backgroundColor: "rgb(42,78,111)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "18",
    type: "custom",
    data: {
      bg_color: "bg-[#66ccb2]",
      codigo: "CD11",
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 7,
      condicion: "carrera",
      materia: "Aprendizaje Automático",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD07|CD08",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        "Clasificación con modelos lineales. Problemas linealmente separables. Clases balanceadas y no balanceadas. Clasificación multi-clase. Los tres acercamientos a la clasificación: función discriminativa, modelos discriminativos y modelos generativos. Discriminullte lineal de Fischer. El algoritmo del perceptrón. Método de descenso por gradiente. La función sigmoidea. Regresión logística. IRLS (cuadrados mínimos iterativamente reponderado; iteratively reweighted least squares). Clasificador de Bayes Ingenuo (Naive Bayes). Clasificadores de margen máximo. Support Vector Machines. El truco del kernel. Bases infinitas de funciones. Márgenes suaves.  \u00c1rboles de decisión. Combinación de modelos. Descomposición en varianza y sesgo. Métodos de ensamble: comités (voto, voto suave), boosting, stacking. Extra trees. Bosques aleatorios (Random Forests). Redes neuronales. Parametrización de las funciones de base. Funciones de activación. Redes neuronales prealimentadas. Capas ocultas y pesos. El perceptrón multicapa. Entrenamiento de redes neuronales.",
    },
    position: {
      x: 100,
      y: 100,
    },
    parentNode: "layer-7",
  },
  {
    id: "19",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: null,
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 7,
      condicion: "carrera",
      materia: "Electiva 3",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD08|CD10",
      ch_presencial: 64.0,
      ch_distancia: 64.0,
      ch_total: 128.0,
      descripcion: null,
    },
    position: {
      x: 700,
      y: 100,
    },
    parentNode: "layer-7",
  },
  {
    id: "20",
    type: "custom",
    data: {
      bg_color: "bg-[#d76060]",
      codigo: null,
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 7,
      condicion: "carrera",
      materia: "Optativa 1",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 96.0,
      ch_distancia: 0.0,
      ch_total: 96.0,
      descripcion: null,
    },
    position: {
      x: 1200,
      y: 100,
    },
    parentNode: "layer-7",
  },
  {
    id: "layer-8",
    data: { label: "Cuatrimestre 8" },
    position: { x: 0, y: 2800 },
    style: {
      backgroundColor: "rgb(42,78,111)",
      width: 1800,
      height: 300,
      fontSize: "32px",
      fontWeight: "bold",
      zIndex: -1,
    },
  },
  {
    id: "21",
    type: "custom",
    data: {
      bg_color: "bg-[#03fbfd]",
      codigo: "CD12",
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 8,
      condicion: "carrera",
      materia: "Aprendizaje Profundo",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD11",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        "Retropropagación. Descenso por gradiente estocástico. Gradientes que se desvanecen. Regularización. Priors gaussianos consistentes. Detención temprana. Dropout. Redes convolucionales. Invariancia de translación. Capas convolucionales y filtros. Pesos compartidos. Mapas de features. Capas de pooling (MaxPooling y AveragePooling). Arquitecturas de redes convolucionales. Encoders-decoders. Redes Neuronales recurrentes. Respuesta finita al impulso (FIR) y respuesta infinita al impulso (IIR). Problemas para entrenar redes recurrentes. Gradientes que se desvanecen. Long short-term memory (LSTM). Celdas LSTM: puertas de entrada, de salida, y de olvido. Pronóstico de series temporales univariadas y multivariadas. Utilización de redes previamente entrenadas. Transfer learning.\n\nEntrenamiento de redes profundas. Inestabilidad de los gradientes y posibles soluciones. Aplicaciones de redes recurrentes. Procesamiento del lenguaje natural. Redes stateless y statefull. Encoders-decoders para modelos de traducción. Redes no supervisadas: Autoencoders. Redes generativas antagónicas (GAN). Aplicaciones de autoencoders y GAN. Entrenamiento de GANs. Aprendizaje por refuerzo. Agente y sistema de recompensas. Aprendizaje por imitación.",
    },
    position: {
      x: 100,
      y: 100,
    },
    parentNode: "layer-8",
  },
  {
    id: "22",
    type: "custom",
    data: {
      bg_color: "bg-[#d76060]",
      codigo: null,
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 8,
      condicion: "carrera",
      materia: "Optativa 3",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 96.0,
      ch_distancia: 0.0,
      ch_total: 96.0,
      descripcion: null,
    },
    position: {
      x: 1000,
      y: 100,
    },
    parentNode: "layer-8",
  },
  {
    id: "23",
    type: "custom",
    data: {
      bg_color: "bg-[#d76060]",
      codigo: null,
      anio: 5,
      ciclo: "Avanzado",
      cuatrimestre: 9,
      condicion: "carrera",
      materia: "Optativa 2",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD12",
      ch_presencial: 64.0,
      ch_distancia: 64.0,
      ch_total: 128.0,
      descripcion: null,
    },
    position: {
      x: 600,
      y: 100,
    },
    parentNode: "layer-8",
  },
  //
  {
    id: "24",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: null,
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Lenguaje SQL",
      formato_didactico: "Asignatura",
      ch_semanal: null,
      ch_cuatrimestral: null,
      creditos: null,
      correlativas: null,
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion: null,
    },
    position: { x: 0, y: 3200 },
  },
  {
    id: "25",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: null,
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Gobernanza de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 2.5,
      ch_cuatrimestral: null,
      creditos: null,
      correlativas: null,
      ch_presencial: 0.0,
      ch_distancia: 2.5,
      ch_total: null,
      descripcion: null,
    },
    position: { x: 350, y: 3200 },
  },
  {
    id: "26",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CB35",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Métodos Numéricos",
      formato_didactico: "Asignatura",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Ecuaciones lineales. Métodos de Jacobi y Gauss-Seidel para sistemas de ecuaciones lineales. Métodos de bisección, secante, de punto fijo y de Newton-Raphson para ecuaciones no lineales. Diferencias divididas. Interpolación polinomial y por funciones spline. Ajuste por mínimos cuadrados. Métodos numéricos para integración. Métodos de los trapecios y de Simson. Cuadraturas gaussianas.Métodos para la resolución numérica de ecuaciones diferenciales ordinarias. Método de Euler, Euler mejorado y de Runge\u2013Kutta. Métodos de predicción-corrección. Métodos de diferencias y elementos finitos para ecuaciones diferenciales. Series temporales y elementos de econometría.",
    },
    position: { x: 700, y: 3200 },
  },
  {
    id: "27",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD15",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Taller de Matemática para Ciencia de Datos",
      formato_didactico: "Taller",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Series numéricas. Criterios de convergencia para series positivas y alternadas. Series funcionales y de potencias. Convergencia puntual y uniforme. Radio de convergencia. Funciones de variable compleja. Transformada de Laplace. Producto de convolución. Transformada de Fourier. Series de Fourier. Convergencia y aproximación de funciones. Espectro de potencias. Conceptos de cálculo complejo.",
    },
    position: { x: 1050, y: 3200 },
  },
  {
    id: "28",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD16",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Series de Tiempo",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CB34",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Modelos autorregresivos. Modelos de promedios móviles. Invertibilidad. Estacionaridad. Modelos ARMA. Estimación de parámetros para modelos autorregresivos. Metodología de Box-Jenkins. Criterios FPE y AIC. Evaluación de los modelos. Gráficos de autocorrelación. Test de Ljung-Box. Modelos no estacionarios ARIMA. Modelos estacionales. Identificación de valores atípicos. Función de transferencia. Modelos autorregresivos vectoriales. Modelos ARIMA vectoriales. Modelos autorregresivos con heterocedasticidad condicional (ARCH). Generalización (GARCH). Visión Bayesiana. Modelos semi-paramétricos y no-paramétricos. State space models.",
    },
    position: { x: 1550, y: 3200 },
  },
  {
    id: "29",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD17",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Neurociencia Computacional",
      formato_didactico: null,
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CB34",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Rese\u00f1a histórica y objetivos de la neurociencia. Introducción a las técnicas modernas de neuro- imágenes en gran escala: resonullcia magnética funcional y técnicas opto-genéticas de registro y perturbación en animales conscientes. Análisis computacional de neuroimágenes. Análisis computacional de se\u00f1ales de calcio en corteza de ratones conscientes. El cerebro como un sistema complejo\ny su modelado matemático. Teoría de redes complejas aplicada al estudio de la función cerebral. Aplicaciones de aprendizaje automático al análisis de datos neuronales. Aplicaciones a la cognición humana, estados patológicos y distintos estados de conciencia.",
    },
    position: { x: 0, y: 3400 },
  },
  {
    id: "30",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD18",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Desarrollo y Gestión de Proyectos de IA",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD05",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Conceptos básicos. Definición de proyecto. El Project Management Institute (PMI) y el PMBOK. Metodología general de desarrollo de productos. Las diez áreas de conocimiento de la gestión de proyectos. Gestión de alcance de los proyectos. Work Breakdown Structure y los Work Packages. Gestión de Plazos. Técnicas de redes. ADM/PDM. Gestión de Costos. Earned Value. \u00cdndices de desempe\u00f1o. Gestión de Calidad. Planeamiento, control y mejora de la calidad. Gestión de Recursos. Gestión de comunicaciones. Gestión de Riesgos. Estudio de casos reales de los sectores público y privado.",
    },
    position: { x: 400, y: 3400 },
  },
  {
    id: "31",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "IE031",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Economía",
      formato_didactico: "Asignatura",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Micro y Macroeconomía. Costos. Formulación y evaluación de proyectos. Finullciamiento, rentabilidad y amortización de proyectos. Análisis de presupuesto.",
    },
    position: { x: 900, y: 3400 },
  },
  {
    id: "32",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD24",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "\u00c9tica en Inteligencia Artificial",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Impacto de la IA en la Sociedad. El mercado del trabajo, inequidad, privacidad, derechos humanos y dignidad. Sesgo de los datos en la IA: reconocimiento facial y discriminación. IA y democracia. Impacto de la IA en el sistema legal, la seguridad, el medio ambiente y el desarrollo sustentable del planeta. Argumentos contra la inteligencia artificial. \u00bfCómo nos protegemos contra las consecuencias imprevistas? Singularidad. \u00bfCómo mantenemos el control de un complejo sistema inteligente? Gobernullza de la IA.: Transparencia, imparcialidad, responsabilidad. Casos de estudio: robots, vehículos autónomos, armas autónomas.",
    },
    position: { x: 1250, y: 3400 },
  },
  {
    id: "33",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD27",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Inglés Técnico",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Conceptos del idioma inglés para el ámbito científico. Lectura y comprensión de textos en inglés.",
    },
    position: { x: 0, y: 3600 },
  },
  {
    id: "34",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "TPI13",
      anio: 3,
      ciclo: null,
      cuatrimestre: 5,
      condicion: "electiva",
      materia: "Algoritmos III",
      formato_didactico: "Asignatura",
      ch_semanal: 10.0,
      ch_cuatrimestral: 160.0,
      creditos: 10.0,
      correlativas: "TPI10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Introducir soluciones cliente/servidor. Tipos de problemas resolubles por medio de este modelo. Soluciones a los problemas que trae la distribución de programas y datos. Resolver por computador problemas de tama\u00f1o mediano, donde se ejerciten las nuevas técnicas aprendidas. Concepto Cliente Servidor. Requerimientos. Transparencia de datos ASN-1, XDR. Plataformas de desarrollo de aplicaciones cliente servidor: Sockets, RPC y NetBIOS. IPC. Sistemas operativos distribuidos. Sistemas de archivos distribuidos y seguridad. Capa de aplicación. Transacciones. Aplicaciones distribuidas tradicionales: Correo electrónico, EDI, Administración de redes, WWW, Java y .NET, Trabajo Cooperativo.",
    },
    position: { x: 350, y: 3600 },
  },
  {
    id: "35",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD26",
      anio: 3,
      ciclo: null,
      cuatrimestre: 5,
      condicion: "electiva",
      materia: "Visualización de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD06",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Infografías vs. gráficos: ejemplos históricos. Joseph Minard, William Playfair, John Snow, Florence Nightingale, Harry Beck). Datos uni- y multivaluados y multivariados. Datos no estructurados. Percepción y visualización: Paletas de color univariadas y bivariadas. Uso eficaz de los atributos visuales (geométricos, cromáticos, retinianos) Aplicaciones en visualización de información. Gramática de gráficos Conectividad: visualización de grafos, redes, árboles. Aplicaciones en redes sociales. Visualización de documentos: sistema de barras apiladas, Mapas Temático, Galaxias de Noticias, Mapas de Kohonen. Visualizando en el espacio: Sistemas de Información Geográfica. Mapas temáticos. Cartogramas. Aplicaciones. Trabajando con modelos: coeficientes de regresión (lineal o logística), residuos. Métodos de visualización de modelos \u201cagnósticos\u201d (feature importance, partial dependence plots, individual conditional expectations, accumulated local effects, etc.).",
    },
    position: { x: 700, y: 3600 },
  },
  {
    id: "36",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD13",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Taller de Análisis de Datos 1",
      formato_didactico: "Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD09|CD10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones de algoritmos de análisis de datos y aprendizaje automáticos a problemas reales. Procesamiento de imágenes y video. Procesamiento del lenguaje natural. Finullzas y comercio.",
    },
    position: { x: 1050, y: 3600 },
  },
  {
    id: "37",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD19",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Infraestructura para la Inteligencia Artifical",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Entornos de procesamiento. Arquitecturas locales. Computación distribuida. Computación en la nube. Características y beneficios. Modelos de Implementación; nubes públicas, nubes privadas, nubes híbridas. Modelos de arquitectura en la nube. Modelos de servicios: Infrastructure as a Service (IaaS), Platform as a Service (PaaS), software as a service (SaaS). Estudio de ejemplos de arquitecturas de servicios. Seguridad y privacidad en la nube.",
    },
    position: { x: 0, y: 3800 },
  },
  {
    id: "38",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD20",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Ciencia de Datos para la Salud",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD09",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones y desarrollos de ciencia de datos, estadística, informática y aprendizaje automático específicas para ciencias de la salud.",
    },
    position: { x: 500, y: 3800 },
  },
  {
    id: "39",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD21",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Ciencia de Datos para la Economía",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones y desarrollos de ciencia de datos, estadística, informática y aprendizaje automático específicas para economía. Econometría.",
    },
    position: { x: 900, y: 3800 },
  },
  {
    id: "40",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD25",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Procesamiento de Lenguaje Natural",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD09",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Fuentes estructuradas, semi-estructuradas y texto libre. Normalización: lematización, stopwords, edit distance, procesamiento de XML. Part of Speech. Expresiones regulares, terminología. Web Scraping: construyendo datasets desde la web. HTML, tags y atributos. Uso de APIs. Space Vector Models (vectorización de texto): Aplicaciones, alcances y limitaciones. Esquemas de asignación de pesos (TF-IDF, Log Entropy). Latent Semantic Analysis, Word2vec, Fasttext. Visualizaciones con MDS y T-SNE. Evaluación de los métodos. Topic modelling: Latent Dirichlet Allocation, Non-Negative Matrix Factorization. Clustering y clasificación de textos: problemas y métodos. Análisis de sentimiento, afecto o subjetividad: Aplicaciones, herramientas, alcances y limitaciones. Lexicons, métodos supervisados.",
    },
    position: { x: 1300, y: 3800 },
  },
  {
    id: "41",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD22",
      anio: 4,
      ciclo: null,
      cuatrimestre: 8,
      condicion: "electiva",
      materia: "Ciencia de Datos para las Finullzas",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD11",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones y desarrollos de ciencia de datos, estadística, informática y aprendizaje automático específicas para las finullzas.",
    },
    position: { x: 0, y: 4000 },
  },
  {
    id: "42",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD14",
      anio: 5,
      ciclo: null,
      cuatrimestre: 9,
      condicion: "electiva",
      materia: "Taller de Análisis de Datos 2",
      formato_didactico: "Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD12",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones de algoritmos de análisis de datos y aprendizaje automáticos a problemas reales. Procesamiento de imágenes y video. Procesamiento del lenguaje natural. Finullzas y comercio.",
    },
    position: { x: 500, y: 4000 },
  },
  {
    id: "43",
    type: "custom",
    data: {
      bg_color: "bg-[#b054d2]",
      codigo: "CD23",
      anio: 5,
      ciclo: null,
      cuatrimestre: 9,
      condicion: "electiva",
      materia: "Temas de Ciencias de la Computación",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD12",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        'Complejidad temporal y espacial de un algoritmo. Técnicas algorítmicas. Algoritmos Recursivos. Técnica "Divide & Conquer". Principio de Optimalidad y Programación Dinámica. Backtracking y Branch and Bound. Algoritmos golosos. Repaso de teoría de grafos y aplicaciones. Algoritmos sobre grafos. Camino mínimo. \u00c1rboles generadores. Problemas de coloreo. Problema del viajante de comercio. Problema del flujo máximo. Problema del "Matching" en grafos. Introducción a la teoría de la complejidad. Clases P y NP. Reducciones Polinomiales. Clases NP-Hard y NP-Completo.',
    },
    position: { x: 900, y: 4000 },
  },
];
