import { useCallback } from "react";
import ReactFlow, {
  useNodesState,
  useEdgesState,
  addEdge,
  MiniMap,
  Controls,
  Node,
  NodeTypes,
  Edge,
  OnConnect,
} from "reactflow";
import CustomNode from "@/components/CustomNode";
import "reactflow/dist/base.css";

const nodeTypes: NodeTypes = {
  custom: CustomNode,
};

const initNodes: Node[] = [
  {
    id: "0",
    type: "custom",
    data: {
      codigo: "N1",
      anio: 1,
      ciclo: "B\u00e1sico",
      cuatrimestre: 1,
      condicion: "carrera",
      materia: "An\u00e1lisis 1",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: null,
      ch_presencial: 128.0,
      ch_distancia: 0.0,
      ch_total: 128.0,
      descripcion:
        "N\u00fameros reales. Propiedades. Intervalos en R. M\u00f3dulo. Concepto de funci\u00f3n. Dominio. Gr\u00e1ficas. Inyectividad y suryectividad. Funci\u00f3n inversa. Funciones polinomiales, racionales, exponenciales y logar\u00edtmicas. L\u00edmites de funciones y Continuidad. Discontinuidades: clasificaci\u00f3n. C\u00e1lculo diferencial. Reglas de derivaci\u00f3n. F\u00f3rmula de Taylor. Aplicaciones de las derivadas. Intervalos de monoton\u00eda. Extremos locales. Extremos absolutos. Concavidad. Puntos de inflexi\u00f3n. An\u00e1lisis de funciones. Gr\u00e1ficas aproximadas. Integral. Primitivas. F\u00f3rmula de Barrow. C\u00e1lculo integral y sus aplicaciones. Integrales impropias. Introducci\u00f3n a las ecuaciones diferenciales ordinarias. M\u00e9todos elementales de integraci\u00f3n. Ecuaciones con variables separables y lineales de primer y de segundo orden.",
    },
    position: {
      x: 0,
      y: 0,
    },
  },
  {
    id: "1",
    type: "custom",
    data: {
      codigo: "CD01",
      anio: 1,
      ciclo: "B\u00e1sico",
      cuatrimestre: 1,
      condicion: "carrera",
      materia: "Introducci\u00f3n a la Ciencia de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "Introducci\u00f3n pr\u00e1ctica al an\u00e1lisis de datos. La relaci\u00f3n entre los datos y los problemas pr\u00e1cticos. Formulaci\u00f3n de preguntas relevantes y pasos de resoluci\u00f3n de un problema realista de ciencia de datos. Presentaci\u00f3n en casos reales. Obtenci\u00f3n y carga de datos. Formato de almacenamiento de datos (csv, tsv, ascii). Encabezados. Formato de los datos (num\u00e9rico, string, fechas y otros). T\u00e9cnicas y herramientas de exploraci\u00f3n y visualizaci\u00f3n de los datos. Evaluaci\u00f3n y correcci\u00f3n de datos. Datos faltantes, datos incorrectos. An\u00e1lisis exploratorio de los datos. Selecci\u00f3n, descubrimiento y dise\u00f1o de features relevantes para la resoluci\u00f3n de un problema dado.\n\nT\u00e9cnicas descriptivas de los datos. Muestras. Valor medio, desv\u00edo est\u00e1ndar. Estad\u00edsticos. Estimadores. Concepto de correlaci\u00f3n y covarianza. Coeficiente de correlaci\u00f3n. Coeficiente de Pearson. Coeficiente de Spearman. Outliers. Sensibilidad de distintos estimadores a los outliers.\n\nModelado de los datos. Modelos estad\u00edsticos b\u00e1sicos. Par\u00e1metros de los modelos. Regresi\u00f3n lineal simple. Interpretaci\u00f3n. Nociones de ajuste por cuadrados m\u00ednimos. Estimadores de los par\u00e1metros del modelo lineal. Supuestos del modelo lineal. Diagn\u00f3sticos del ajuste. Evaluaci\u00f3n del modelo. Introducci\u00f3n b\u00e1sica a test estad\u00edsticos, residuos, QQplots. Residuos. Leverage. Outliers. Extensi\u00f3n de los modelos. Modelos aditivos. Regresi\u00f3n lineal m\u00faltiple.",
    },
    position: {
      x: 200,
      y: 0,
    },
  },
  {
    id: "2",
    type: "custom",
    data: {
      codigo: "CD02",
      anio: 1,
      ciclo: "B\u00e1sico",
      cuatrimestre: 1,
      condicion: "carrera",
      materia: "Programaci\u00f3n 1",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "Introducci\u00f3n al pensamiento algor\u00edtmico. Presentaci\u00f3n del lenguaje de programaci\u00f3n Python. Diferentes entornos de programaci\u00f3n (consola, IDE, notebooks). Sintaxis del lenguaje. Tipos de datos b\u00e1sicos. Funciones y documentaci\u00f3n. Estructuras de control b\u00e1sicas: condicionales (if; while), iteraciones (for), comprensi\u00f3n de listas. Estructuras de datos: diccionarios, listas, tuplas, vectores, matrices y \u00e1rboles. M\u00f3dulos y paquetes. Concepto de namespace. Introducci\u00f3n a la programaci\u00f3n orientada a objetos. Conceptos b\u00e1sicos, m\u00e9todos, atributos, herencia. Estructuras de lectura y escritura de datos. Visualizaci\u00f3n de datos. Testeo y debuggeo de los programas. Manejo de excepciones. Control de flujos. Introducci\u00f3n a paquetes de c\u00e1lculo (numpy) y visualizaci\u00f3n (matplotlib). Elementos de c\u00e1lculo num\u00e9rico para an\u00e1lisis matem\u00e1tico.",
    },
    position: {
      x: -200,
      y: 0,
    },
  },
  {
    id: "3",
    type: "custom",
    data: {
      codigo: "N10",
      anio: 1,
      ciclo: "B\u00e1sico",
      cuatrimestre: 2,
      condicion: "carrera",
      materia: "An\u00e1lisis 2",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "N1",
      ch_presencial: 128.0,
      ch_distancia: 0.0,
      ch_total: 128.0,
      descripcion:
        "Funciones vectoriales reales. L\u00edmites y continuidad. C\u00e1lculo diferencial vectorial. Regla de la cadena. Funciones impl\u00edcitas. Curvas y superficies parametrizadas.  F\u00f3rmula de Taylor vectorial. Plano tangente. Problemas de m\u00e1ximos y m\u00ednimos. Multiplicadores de Lagrange. Campos escalares y vectoriales. Potencial. Campo tangente y normal. Formas diferenciales exactas. An\u00e1lisis geom\u00e9trico de ecuaciones diferenciales. Cambio de coordenadas. Coordenadas polares, esf\u00e9ricas y cil\u00edndricas. Integrales m\u00faltiples. Integrales param\u00e9tricas, curvil\u00edneas y de superficie. Aplicaciones geom\u00e9tricas. Operadores gradiente, divergencia, rotor y laplaciano.",
    },
    position: {
      x: 0,
      y: -300,
    },
  },
  {
    id: "4",
    type: "custom",
    data: {
      codigo: "CD03",
      anio: 1,
      ciclo: "B\u00e1sico",
      cuatrimestre: 2,
      condicion: "carrera",
      materia: "Matem\u00e1tica Discreta",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "N1",
      ch_presencial: 96.0,
      ch_distancia: 32.0,
      ch_total: 128.0,
      descripcion:
        "Introducci\u00f3n a la Teor\u00eda de N\u00fameros, L\u00f3gica proporcional cl\u00e1sica y de Predicados de primer orden. Combinatoria. Conjuntos, relaciones y funciones. Relaciones de recurrencia. Algebra de Boole. Teor\u00eda de Grafos- Arboles. Sistemas y c\u00f3digos de numeraci\u00f3n. Polinomios. Geometr\u00eda en el plano y el espacio. Vectores. Producto escalar. Magnitud, distancia y \u00e1ngulo. Rectas y planos.  Paralelismo y perpendicularidad. Matrices. Operaciones aritm\u00e9ticas matriciales. Transposici\u00f3n. Matriz inversa. Sistemas de ecuaciones lineales. Eliminaci\u00f3n gaussiana. Determinulltes. Espacios vectoriales R^n. Sub-espacios. Generadores. Independencia lineal. Bases y dimensi\u00f3n. Intersecci\u00f3n, suma y suma directa de sub-espacios. Espacios vectoriales generales. Transformaciones lineales. Producto interno. Ortogonalidad. Bases. Matrices asociadas a una transformaci\u00f3n lineal. Autovalores y autovectores. Diagonalizaci\u00f3n de matrices.",
    },
    position: {
      x: 200,
      y: -300,
    },
  },
  {
    id: "5",
    type: "custom",
    data: {
      codigo: "CD04",
      anio: 1,
      ciclo: "B\u00e1sico",
      cuatrimestre: 2,
      condicion: "carrera",
      materia: "Introducci\u00f3n al Aprendizaje Autom\u00e1tico",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "N1|CD01|CD02",
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "Funcionamiento de los algoritmos de aprendizaje autom\u00e1tico. Validez, aplicabilidad, y limitaciones. Conjunto de datos de entrenamiento, validaci\u00f3n y testeo. Repaso de regresi\u00f3n lineal. Funciones de error. Sobreajuste. Regularizaci\u00f3n. Regresi\u00f3n ridge y lasso. Aplicaci\u00f3n de algoritmos de aprendizaje autom\u00e1tico: regresi\u00f3n y clasificaci\u00f3n lineal; discriminullte linear de Fischer; perceptr\u00f3n; support vector machine; \u00e1rboles de decisi\u00f3n; naive Bayes.",
    },
    position: {
      x: -200,
      y: -300,
    },
  },
  {
    id: "6",
    type: "custom",
    data: {
      codigo: "CD05",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 3,
      condicion: "carrera",
      materia: "Infraestructura para Ciencia de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD02",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        'Funcionamiento de una computadora. Unidad de procesamiento central. Memoria RAM. Redes. Tiempo de latencia. Recursos compartidos. Clusters de c\u00e1lculo. C\u00e1lculo usando Unidades de procesamiento de gr\u00e1ficos (GPU). Nociones de escala y capacidades. Conceptos b\u00e1sicos de "cloud computing". Diferencias y ventajas con respecto a las infraestructuras tradicionales. Almacenamiento definido por software. Soluciones de redes definidas por software. Sistemas operativos para servidores. Virtualizaci\u00f3n. Servicios de red. Servicios de directorio (Active Directory, OpenLDAP)',
    },
    position: {
      x: -200,
      y: -600,
    },
  },
  {
    id: "7",
    type: "custom",
    data: {
      codigo: "TPI07",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 3,
      condicion: "carrera",
      materia: "Algoritmos I",
      formato_didactico: "Asignatura",
      ch_semanal: 10.0,
      ch_cuatrimestral: 160.0,
      creditos: 10.0,
      correlativas: "N1",
      ch_presencial: 160.0,
      ch_distancia: 0.0,
      ch_total: 160.0,
      descripcion:
        "Especificaci\u00f3n e implementaci\u00f3n de programas. Correcci\u00f3n de programas. Tipos de datos.  Tipos abstractos. Tratamiento de secuencias. Archivos secuenciales.",
    },
    position: {
      x: 0,
      y: -600,
    },
  },
  {
    id: "8",
    type: "custom",
    data: {
      codigo: "CB34",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 3,
      condicion: "carrera",
      materia: "Probabilidad y Estad\u00edstica",
      formato_didactico: "Asignatura",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: 64.0,
      ch_distancia: 0.0,
      ch_total: 64.0,
      descripcion:
        "Experimentos aleatorios. Frecuencias relativas. Modelo de Laplace.  Probabilidad. Independencia y probabilidad condicional. Teorema de Bayes. C\u00e1lculo de probabilidades. Variables aleatorias. Funciones de densidad y de probabilidad. Funciones de distribuci\u00f3n.  Principales distribuciones discretas y continuas. Variables aleatorias vectoriales.  Distribuciones conjuntas y marginales.  Momentos de primer y segundo orden. Ley de Grandes N\u00fameros, Teorema Central del L\u00edmite. Correlaci\u00f3n. Nociones de procesos estoc\u00e1sticos. Funci\u00f3n de autocorrelaci\u00f3n. Procesos estacionarios. Regresi\u00f3n lineal. Nociones de estad\u00edstica descriptiva y param\u00e9trica. Test de hip\u00f3tesis.",
    },
    position: {
      x: 200,
      y: -600,
    },
  },
  {
    id: "9",
    type: "custom",
    data: {
      codigo: "CD06",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 4,
      condicion: "carrera",
      materia: "Estad\u00edstica e Inferencia I",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CB34|CD03",
      ch_presencial: 0.0,
      ch_distancia: 128.0,
      ch_total: 128.0,
      descripcion:
        "Conceptos te\u00f3ricos. Estimaci\u00f3n Puntual. Estad\u00edsticos suficientes y completos. Estimadores de momentos y de M\u00e1xima Verosimilitud. Regiones de confianza.\n\nDistribuciones multivariadas. Normal multivariada. Wishart\n\nRegresi\u00f3n lineal simple y m\u00faltiple. Modelos param\u00e9tricos lineales. Regresi\u00f3n paso a paso (stepwise regression). Regresi\u00f3n lineal multivariada. Modelos lineales generalizados.\n\nTeor\u00eda de la probabilidad como una extensi\u00f3n de la l\u00f3gica. Razonamiento en presencia de incertidumbre. L\u00f3gica bayesiana. Teorema de Bayes. Bayes como un modelo de aprendizaje. Elementos de estad\u00edstica. Verosimilitud. Priors. Posteriors. Inferencia bayesiana. Modelos con un solo par\u00e1metro. Resultados anal\u00edticos. Priors conjugados. Familia exponencial. Testeo A/B bayesiano. Visi\u00f3n bayesiana de la regresi\u00f3n con modelos lineales. Construcci\u00f3n de modelos multi-param\u00e9tricos. Modelos de mixturas finitas. Mixturas gaussianas. Responsabilidades. El algoritmo esperanza-maximizaci\u00f3n (EM). Generalizaci\u00f3n a los modelos de variables latentes. Detecci\u00f3n de anomal\u00edas. Validaci\u00f3n estad\u00edstica de los modelos. Distribuci\u00f3n predictiva posterior. Validaci\u00f3n cruzada. Comparaci\u00f3n de modelos bayesiana. Consideraci\u00f3n de la complejidad de los modelos. Nociones de teor\u00eda de la decisi\u00f3n. Modelos gr\u00e1ficos.",
    },
    position: {
      x: 0,
      y: -900,
    },
  },
  {
    id: "10",
    type: "custom",
    data: {
      codigo: "TPI10",
      anio: 2,
      ciclo: "General",
      cuatrimestre: 4,
      condicion: "carrera",
      materia: "Algoritmos II",
      formato_didactico: "Asignatura",
      ch_semanal: 9.0,
      ch_cuatrimestral: 144.0,
      creditos: 9.0,
      correlativas: "N10|CD03|TPI07",
      ch_presencial: 144.0,
      ch_distancia: 0.0,
      ch_total: 144.0,
      descripcion:
        "Recursi\u00f3n. Tipos de datos abstractos pila, cola, diccionario, \u00e1rbol, grafo, etc. Metodolog\u00edas de especificaci\u00f3n formal. Lenguajes de especificaci\u00f3n formal. Implementaciones.",
    },
    position: {
      x: 200,
      y: -900,
    },
  },
  {
    id: "11",
    type: "custom",
    data: {
      codigo: null,
      anio: 2,
      ciclo: "General",
      cuatrimestre: 4,
      condicion: "carrera",
      materia: "Electiva 1",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: null,
      ch_presencial: 0.0,
      ch_distancia: 64.0,
      ch_total: 64.0,
      descripcion: null,
    },
    position: {
      x: -200,
      y: -900,
    },
  },
  {
    id: "12",
    type: "custom",
    data: {
      codigo: "CD07",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 5,
      condicion: "carrera",
      materia: "Estad\u00edstica e Inferencia II",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD06",
      ch_presencial: 0.0,
      ch_distancia: 128.0,
      ch_total: 128.0,
      descripcion:
        "Revisi\u00f3n de la regresi\u00f3n con modelos lineales bayesiana.  Modelos generativos. Modelos de variables latentes. Responsabilidades. Generalizaci\u00f3n del algoritmo esperanza-maximizaci\u00f3n (EM). Modelos no param\u00e9tricos. Estimaci\u00f3n de densidades. M\u00e9todos de kernel. K-means. Procesos gaussianos. Procesos de Dirichlet. Modelos jer\u00e1rquicos bayesianos.",
    },
    position: {
      x: 0,
      y: -1200,
    },
  },
  {
    id: "13",
    type: "custom",
    data: {
      codigo: "CD08",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 5,
      condicion: "carrera",
      materia: "Programaci\u00f3n 2",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD02|TPI10",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        "An\u00e1lisis de rendimiento de software (perfilaje). Manejo de aserciones. Utilizaci\u00f3n avanzada de las clases en python. Herencia m\u00faltiple. Variables privadas. Iteradores y generadores. Decoradores. Uso y funcionalidad de los decoradores. Ambientes virtuales. Paquetes de python para la ciencia de datos: pandas, seaborn. Aplicaciones. Utilizaci\u00f3n de c\u00f3digo C, C++, y Fortran desde python.\n\nAmbientes integrales de desarrollo (IDE). Nociones vinculadas con los sistemas de control de versi\u00f3n. Introducci\u00f3n al lenguaje de an\u00e1lisis estad\u00edstico R.",
    },
    position: {
      x: 200,
      y: -1200,
    },
  },
  {
    id: "14",
    type: "custom",
    data: {
      codigo: null,
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 5,
      condicion: "carrera",
      materia: "Electiva 2",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 96.0,
      ch_distancia: 0.0,
      ch_total: 96.0,
      descripcion: null,
    },
    position: {
      x: -200,
      y: -1200,
    },
  },
  {
    id: "15",
    type: "custom",
    data: {
      codigo: "CD09",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 6,
      condicion: "carrera",
      materia: "Ciencia de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD07|TPI10",
      ch_presencial: 32.0,
      ch_distancia: 96.0,
      ch_total: 128.0,
      descripcion:
        "La materia se propone presentar una serie de t\u00e9cnicas de c\u00e1lculo, preparaci\u00f3n de datos y visualizaci\u00f3n, necesarias para llevar adelante an\u00e1lisis de datos en situaciones de la vida real.\n\nT\u00e9cnicas de muestreo. Muestreo simple con y sin reposici\u00f3n. Muestreo por rechazo. Muestreo de importancia. Importance-sampling-resampling. Gibbs sampling. Markov Chain Monte Carlo. Metropolis Hastings. Muestreo con ensambles.\n\nExtracci\u00f3n de features y reducci\u00f3n de la dimensionalidad. Variables latentes continuas. An\u00e1lisis en componentes principales (PCA). PCA probabil\u00edstico. PCA bayesiano. PCA con n\u00facleos (kernel PCA). Modelos con variables latentes no lineales. An\u00e1lisis de componentes independientes.\n\nInferencia aproximada. M\u00e9todos variacionales bayesianos. C\u00e1lculo Bayesiano Aproximado (ABC). Nociones del lenguaje de programaci\u00f3n estad\u00edstico R y de la plataforma Stan.\n\nVisualizaci\u00f3n. Acercamientos modernos a la visualizaci\u00f3n de datos. Biplots, etc.",
    },
    position: {
      x: 0,
      y: -1500,
    },
  },
  {
    id: "16",
    type: "custom",
    data: {
      codigo: "TPI14",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 6,
      condicion: "carrera",
      materia: "Bases de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "TPI10",
      ch_presencial: 128.0,
      ch_distancia: 0.0,
      ch_total: 128.0,
      descripcion:
        "Funciones de los sistemas de Base de Datos. Modelos de datos. Lenguajes de consulta. Dise\u00f1o de Base de Datos. Estructuras f\u00edsicas y l\u00f3gicas de datos. Optimizaci\u00f3n de consultas. Transacciones. Concurrencia y recuperaci\u00f3n. Implementaciones.",
    },
    position: {
      x: 200,
      y: -1500,
    },
  },
  {
    id: "17",
    type: "custom",
    data: {
      codigo: "CD10",
      anio: 3,
      ciclo: "Avanzado",
      cuatrimestre: 6,
      condicion: "carrera",
      materia: "Ingenier\u00eda de Software",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD08",
      ch_presencial: 64.0,
      ch_distancia: 32.0,
      ch_total: 96.0,
      descripcion:
        "El proceso de software. Ciclos de vida del software. Pr\u00e1cticas DevOps de desarrollo (Dev) y operaciones (Ops). Pr\u00e1cticas \u00e1giles. Ingenier\u00eda de requerimientos. Arquitectura y dise\u00f1o. Patrones. Conceptos de arquitecturas orientadas a servicios. Reingenier\u00eda de software. Calidad de software: del producto y del proceso. Dise\u00f1o centrado en el usuario. Administraci\u00f3n y control de proyectos. Nociones de auditor\u00eda y peritaje. Teor\u00eda general de sistemas. Sistemas de informaci\u00f3n. Privacidad integridad y seguridad en sistemas de informaci\u00f3n. Nociones de sistemas colaborativos. Documentaci\u00f3n. Responsabilidad y \u00e9tica profesional. Computaci\u00f3n y sociedad. Propiedad intelectual, licenciamiento de software y contratos inform\u00e1ticos. Aspectos legales.\n\nNetDevOps, Redes basadas en la intenci\u00f3n, Redes basadas en la experiencia. Redes definidas por software. Redes autoconfigurables.",
    },
    position: {
      x: -200,
      y: -1500,
    },
  },
  {
    id: "18",
    type: "custom",
    data: {
      codigo: "CD11",
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 7,
      condicion: "carrera",
      materia: "Aprendizaje Autom\u00e1tico",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD07|CD08",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        "Clasificaci\u00f3n con modelos lineales. Problemas linealmente separables. Clases balanceadas y no balanceadas. Clasificaci\u00f3n multi-clase. Los tres acercamientos a la clasificaci\u00f3n: funci\u00f3n discriminativa, modelos discriminativos y modelos generativos. Discriminullte lineal de Fischer. El algoritmo del perceptr\u00f3n. M\u00e9todo de descenso por gradiente. La funci\u00f3n sigmoidea. Regresi\u00f3n log\u00edstica. IRLS (cuadrados m\u00ednimos iterativamente reponderado; iteratively reweighted least squares). Clasificador de Bayes Ingenuo (Naive Bayes). Clasificadores de margen m\u00e1ximo. Support Vector Machines. El truco del kernel. Bases infinitas de funciones. M\u00e1rgenes suaves.  \u00c1rboles de decisi\u00f3n. Combinaci\u00f3n de modelos. Descomposici\u00f3n en varianza y sesgo. M\u00e9todos de ensamble: comit\u00e9s (voto, voto suave), boosting, stacking. Extra trees. Bosques aleatorios (Random Forests). Redes neuronales. Parametrizaci\u00f3n de las funciones de base. Funciones de activaci\u00f3n. Redes neuronales prealimentadas. Capas ocultas y pesos. El perceptr\u00f3n multicapa. Entrenamiento de redes neuronales.",
    },
    position: {
      x: 0,
      y: -1800,
    },
  },
  {
    id: "19",
    type: "custom",
    data: {
      codigo: null,
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 7,
      condicion: "carrera",
      materia: "Electiva 3",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD08|CD10",
      ch_presencial: 64.0,
      ch_distancia: 64.0,
      ch_total: 128.0,
      descripcion: null,
    },
    position: {
      x: -200,
      y: -1800,
    },
  },
  {
    id: "20",
    type: "custom",
    data: {
      codigo: null,
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 7,
      condicion: "carrera",
      materia: "Optativa 1",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 96.0,
      ch_distancia: 0.0,
      ch_total: 96.0,
      descripcion: null,
    },
    position: {
      x: 200,
      y: -1800,
    },
  },
  {
    id: "21",
    type: "custom",
    data: {
      codigo: "CD12",
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 8,
      condicion: "carrera",
      materia: "Aprendizaje Profundo",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD11",
      ch_presencial: 0.0,
      ch_distancia: 96.0,
      ch_total: 96.0,
      descripcion:
        "Retropropagaci\u00f3n. Descenso por gradiente estoc\u00e1stico. Gradientes que se desvanecen. Regularizaci\u00f3n. Priors gaussianos consistentes. Detenci\u00f3n temprana. Dropout. Redes convolucionales. Invariancia de translaci\u00f3n. Capas convolucionales y filtros. Pesos compartidos. Mapas de features. Capas de pooling (MaxPooling y AveragePooling). Arquitecturas de redes convolucionales. Encoders-decoders. Redes Neuronales recurrentes. Respuesta finita al impulso (FIR) y respuesta infinita al impulso (IIR). Problemas para entrenar redes recurrentes. Gradientes que se desvanecen. Long short-term memory (LSTM). Celdas LSTM: puertas de entrada, de salida, y de olvido. Pron\u00f3stico de series temporales univariadas y multivariadas. Utilizaci\u00f3n de redes previamente entrenadas. Transfer learning.\n\nEntrenamiento de redes profundas. Inestabilidad de los gradientes y posibles soluciones. Aplicaciones de redes recurrentes. Procesamiento del lenguaje natural. Redes stateless y statefull. Encoders-decoders para modelos de traducci\u00f3n. Redes no supervisadas: Autoencoders. Redes generativas antag\u00f3nicas (GAN). Aplicaciones de autoencoders y GAN. Entrenamiento de GANs. Aprendizaje por refuerzo. Agente y sistema de recompensas. Aprendizaje por imitaci\u00f3n.",
    },
    position: {
      x: 0,
      y: -2100,
    },
  },
  {
    id: "22",
    type: "custom",
    data: {
      codigo: null,
      anio: 4,
      ciclo: "Avanzado",
      cuatrimestre: 8,
      condicion: "carrera",
      materia: "Optativa 3",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: 96.0,
      ch_distancia: 0.0,
      ch_total: 96.0,
      descripcion: null,
    },
    position: {
      x: 200,
      y: -2100,
    },
  },
  {
    id: "23",
    type: "custom",
    data: {
      codigo: null,
      anio: 5,
      ciclo: "Avanzado",
      cuatrimestre: 9,
      condicion: "carrera",
      materia: "Optativa 2",
      formato_didactico: "Asignatura o Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD12",
      ch_presencial: 64.0,
      ch_distancia: 64.0,
      ch_total: 128.0,
      descripcion: null,
    },
    position: {
      x: 0,
      y: -2400,
    },
  },
  {
    id: "24",
    type: "custom",
    data: {
      codigo: null,
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Lenguaje SQL",
      formato_didactico: "Asignatura",
      ch_semanal: null,
      ch_cuatrimestral: null,
      creditos: null,
      correlativas: null,
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion: null,
    },
    position: {
      x: 400,
      y: -900,
    },
  },
  {
    id: "25",
    type: "custom",
    data: {
      codigo: null,
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Gobernanza de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 2.5,
      ch_cuatrimestral: null,
      creditos: null,
      correlativas: null,
      ch_presencial: 0.0,
      ch_distancia: 2.5,
      ch_total: null,
      descripcion: null,
    },
    position: {
      x: 600,
      y: -900,
    },
  },
  {
    id: "26",
    type: "custom",
    data: {
      codigo: "CB35",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "M\u00e9todos Num\u00e9ricos",
      formato_didactico: "Asignatura",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Ecuaciones lineales. M\u00e9todos de Jacobi y Gauss-Seidel para sistemas de ecuaciones lineales. M\u00e9todos de bisecci\u00f3n, secante, de punto fijo y de Newton-Raphson para ecuaciones no lineales. Diferencias divididas. Interpolaci\u00f3n polinomial y por funciones spline. Ajuste por m\u00ednimos cuadrados. M\u00e9todos num\u00e9ricos para integraci\u00f3n. M\u00e9todos de los trapecios y de Simson. Cuadraturas gaussianas.M\u00e9todos para la resoluci\u00f3n num\u00e9rica de ecuaciones diferenciales ordinarias. M\u00e9todo de Euler, Euler mejorado y de Runge\u2013Kutta. M\u00e9todos de predicci\u00f3n-correcci\u00f3n. M\u00e9todos de diferencias y elementos finitos para ecuaciones diferenciales. Series temporales y elementos de econometr\u00eda.",
    },
    position: {
      x: 800,
      y: -900,
    },
  },
  {
    id: "27",
    type: "custom",
    data: {
      codigo: "CD15",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Taller de Matem\u00e1tica para Ciencia de Datos",
      formato_didactico: "Taller",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Series num\u00e9ricas. Criterios de convergencia para series positivas y alternadas. Series funcionales y de potencias. Convergencia puntual y uniforme. Radio de convergencia. Funciones de variable compleja. Transformada de Laplace. Producto de convoluci\u00f3n. Transformada de Fourier. Series de Fourier. Convergencia y aproximaci\u00f3n de funciones. Espectro de potencias. Conceptos de c\u00e1lculo complejo.",
    },
    position: {
      x: 1000,
      y: -900,
    },
  },
  {
    id: "28",
    type: "custom",
    data: {
      codigo: "CD16",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Series de Tiempo",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CB34",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Modelos autorregresivos. Modelos de promedios m\u00f3viles. Invertibilidad. Estacionaridad. Modelos ARMA. Estimaci\u00f3n de par\u00e1metros para modelos autorregresivos. Metodolog\u00eda de Box-Jenkins. Criterios FPE y AIC. Evaluaci\u00f3n de los modelos. Gr\u00e1ficos de autocorrelaci\u00f3n. Test de Ljung-Box. Modelos no estacionarios ARIMA. Modelos estacionales. Identificaci\u00f3n de valores at\u00edpicos. Funci\u00f3n de transferencia. Modelos autorregresivos vectoriales. Modelos ARIMA vectoriales. Modelos autorregresivos con heterocedasticidad condicional (ARCH). Generalizaci\u00f3n (GARCH). Visi\u00f3n Bayesiana. Modelos semi-param\u00e9tricos y no-param\u00e9tricos. State space models.",
    },
    position: {
      x: 1200,
      y: -900,
    },
  },
  {
    id: "29",
    type: "custom",
    data: {
      codigo: "CD17",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Neurociencia Computacional",
      formato_didactico: null,
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CB34",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Rese\u00f1a hist\u00f3rica y objetivos de la neurociencia. Introducci\u00f3n a las t\u00e9cnicas modernas de neuro- im\u00e1genes en gran escala: resonullcia magn\u00e9tica funcional y t\u00e9cnicas opto-gen\u00e9ticas de registro y perturbaci\u00f3n en animales conscientes. An\u00e1lisis computacional de neuroim\u00e1genes. An\u00e1lisis computacional de se\u00f1ales de calcio en corteza de ratones conscientes. El cerebro como un sistema complejo\ny su modelado matem\u00e1tico. Teor\u00eda de redes complejas aplicada al estudio de la funci\u00f3n cerebral. Aplicaciones de aprendizaje autom\u00e1tico al an\u00e1lisis de datos neuronales. Aplicaciones a la cognici\u00f3n humana, estados patol\u00f3gicos y distintos estados de conciencia.",
    },
    position: {
      x: -400,
      y: -900,
    },
  },
  {
    id: "30",
    type: "custom",
    data: {
      codigo: "CD18",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Desarrollo y Gesti\u00f3n de Proyectos de IA",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD05",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Conceptos b\u00e1sicos. Definici\u00f3n de proyecto. El Project Management Institute (PMI) y el PMBOK. Metodolog\u00eda general de desarrollo de productos. Las diez \u00e1reas de conocimiento de la gesti\u00f3n de proyectos. Gesti\u00f3n de alcance de los proyectos. Work Breakdown Structure y los Work Packages. Gesti\u00f3n de Plazos. T\u00e9cnicas de redes. ADM/PDM. Gesti\u00f3n de Costos. Earned Value. \u00cdndices de desempe\u00f1o. Gesti\u00f3n de Calidad. Planeamiento, control y mejora de la calidad. Gesti\u00f3n de Recursos. Gesti\u00f3n de comunicaciones. Gesti\u00f3n de Riesgos. Estudio de casos reales de los sectores p\u00fablico y privado.",
    },
    position: {
      x: -600,
      y: -900,
    },
  },
  {
    id: "31",
    type: "custom",
    data: {
      codigo: "IE031",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Econom\u00eda",
      formato_didactico: "Asignatura",
      ch_semanal: 4.0,
      ch_cuatrimestral: 64.0,
      creditos: 4.0,
      correlativas: "N10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Micro y Macroeconom\u00eda. Costos. Formulaci\u00f3n y evaluaci\u00f3n de proyectos. Finullciamiento, rentabilidad y amortizaci\u00f3n de proyectos. An\u00e1lisis de presupuesto.",
    },
    position: {
      x: -800,
      y: -900,
    },
  },
  {
    id: "32",
    type: "custom",
    data: {
      codigo: "CD24",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "\u00c9tica en Inteligencia Artificial",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Impacto de la IA en la Sociedad. El mercado del trabajo, inequidad, privacidad, derechos humanos y dignidad. Sesgo de los datos en la IA: reconocimiento facial y discriminaci\u00f3n. IA y democracia. Impacto de la IA en el sistema legal, la seguridad, el medio ambiente y el desarrollo sustentable del planeta. Argumentos contra la inteligencia artificial. \u00bfC\u00f3mo nos protegemos contra las consecuencias imprevistas? Singularidad. \u00bfC\u00f3mo mantenemos el control de un complejo sistema inteligente? Gobernullza de la IA.: Transparencia, imparcialidad, responsabilidad. Casos de estudio: robots, veh\u00edculos aut\u00f3nomos, armas aut\u00f3nomas.",
    },
    position: {
      x: -1000,
      y: -900,
    },
  },
  {
    id: "33",
    type: "custom",
    data: {
      codigo: "CD27",
      anio: 2,
      ciclo: null,
      cuatrimestre: 4,
      condicion: "electiva",
      materia: "Ingl\u00e9s T\u00e9cnico",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: null,
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Conceptos del idioma ingl\u00e9s para el \u00e1mbito cient\u00edfico. Lectura y comprensi\u00f3n de textos en ingl\u00e9s.",
    },
    position: {
      x: -1200,
      y: -900,
    },
  },
  {
    id: "34",
    type: "custom",
    data: {
      codigo: "TPI13",
      anio: 3,
      ciclo: null,
      cuatrimestre: 5,
      condicion: "electiva",
      materia: "Algoritmos III",
      formato_didactico: "Asignatura",
      ch_semanal: 10.0,
      ch_cuatrimestral: 160.0,
      creditos: 10.0,
      correlativas: "TPI10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Introducir soluciones cliente/servidor. Tipos de problemas resolubles por medio de este modelo. Soluciones a los problemas que trae la distribuci\u00f3n de programas y datos. Resolver por computador problemas de tama\u00f1o mediano, donde se ejerciten las nuevas t\u00e9cnicas aprendidas. Concepto Cliente Servidor. Requerimientos. Transparencia de datos ASN-1, XDR. Plataformas de desarrollo de aplicaciones cliente servidor: Sockets, RPC y NetBIOS. IPC. Sistemas operativos distribuidos. Sistemas de archivos distribuidos y seguridad. Capa de aplicaci\u00f3n. Transacciones. Aplicaciones distribuidas tradicionales: Correo electr\u00f3nico, EDI, Administraci\u00f3n de redes, WWW, Java y .NET, Trabajo Cooperativo.",
    },
    position: {
      x: -400,
      y: -1200,
    },
  },
  {
    id: "35",
    type: "custom",
    data: {
      codigo: "CD26",
      anio: 3,
      ciclo: null,
      cuatrimestre: 5,
      condicion: "electiva",
      materia: "Visualizaci\u00f3n de Datos",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD06",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Infograf\u00edas vs. gr\u00e1ficos: ejemplos hist\u00f3ricos. Joseph Minard, William Playfair, John Snow, Florence Nightingale, Harry Beck). Datos uni- y multivaluados y multivariados. Datos no estructurados. Percepci\u00f3n y visualizaci\u00f3n: Paletas de color univariadas y bivariadas. Uso eficaz de los atributos visuales (geom\u00e9tricos, crom\u00e1ticos, retinianos) Aplicaciones en visualizaci\u00f3n de informaci\u00f3n. Gram\u00e1tica de gr\u00e1ficos Conectividad: visualizaci\u00f3n de grafos, redes, \u00e1rboles. Aplicaciones en redes sociales. Visualizaci\u00f3n de documentos: sistema de barras apiladas, Mapas Tem\u00e1tico, Galaxias de Noticias, Mapas de Kohonen. Visualizando en el espacio: Sistemas de Informaci\u00f3n Geogr\u00e1fica. Mapas tem\u00e1ticos. Cartogramas. Aplicaciones. Trabajando con modelos: coeficientes de regresi\u00f3n (lineal o log\u00edstica), residuos. M\u00e9todos de visualizaci\u00f3n de modelos \u201cagn\u00f3sticos\u201d (feature importance, partial dependence plots, individual conditional expectations, accumulated local effects, etc.).",
    },
    position: {
      x: -600,
      y: -1200,
    },
  },
  {
    id: "36",
    type: "custom",
    data: {
      codigo: "CD13",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Taller de An\u00e1lisis de Datos 1",
      formato_didactico: "Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD09|CD10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones de algoritmos de an\u00e1lisis de datos y aprendizaje autom\u00e1ticos a problemas reales. Procesamiento de im\u00e1genes y video. Procesamiento del lenguaje natural. Finullzas y comercio.",
    },
    position: {
      x: 400,
      y: -1800,
    },
  },
  {
    id: "37",
    type: "custom",
    data: {
      codigo: "CD19",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Infraestructura para la Inteligencia Artifical",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Entornos de procesamiento. Arquitecturas locales. Computaci\u00f3n distribuida. Computaci\u00f3n en la nube. Caracter\u00edsticas y beneficios. Modelos de Implementaci\u00f3n; nubes p\u00fablicas, nubes privadas, nubes h\u00edbridas. Modelos de arquitectura en la nube. Modelos de servicios: Infrastructure as a Service (IaaS), Platform as a Service (PaaS), software as a service (SaaS). Estudio de ejemplos de arquitecturas de servicios. Seguridad y privacidad en la nube.",
    },
    position: {
      x: 600,
      y: -1800,
    },
  },
  {
    id: "38",
    type: "custom",
    data: {
      codigo: "CD20",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Ciencia de Datos para la Salud",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD09",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones y desarrollos de ciencia de datos, estad\u00edstica, inform\u00e1tica y aprendizaje autom\u00e1tico espec\u00edficas para ciencias de la salud.",
    },
    position: {
      x: 800,
      y: -1800,
    },
  },
  {
    id: "39",
    type: "custom",
    data: {
      codigo: "CD21",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Ciencia de Datos para la Econom\u00eda",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD10",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones y desarrollos de ciencia de datos, estad\u00edstica, inform\u00e1tica y aprendizaje autom\u00e1tico espec\u00edficas para econom\u00eda. Econometr\u00eda.",
    },
    position: {
      x: 1000,
      y: -1800,
    },
  },
  {
    id: "40",
    type: "custom",
    data: {
      codigo: "CD25",
      anio: 4,
      ciclo: null,
      cuatrimestre: 7,
      condicion: "electiva",
      materia: "Procesamiento de Lenguaje Natural",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD09",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Fuentes estructuradas, semi-estructuradas y texto libre. Normalizaci\u00f3n: lematizaci\u00f3n, stopwords, edit distance, procesamiento de XML. Part of Speech. Expresiones regulares, terminolog\u00eda. Web Scraping: construyendo datasets desde la web. HTML, tags y atributos. Uso de APIs. Space Vector Models (vectorizaci\u00f3n de texto): Aplicaciones, alcances y limitaciones. Esquemas de asignaci\u00f3n de pesos (TF-IDF, Log Entropy). Latent Semantic Analysis, Word2vec, Fasttext. Visualizaciones con MDS y T-SNE. Evaluaci\u00f3n de los m\u00e9todos. Topic modelling: Latent Dirichlet Allocation, Non-Negative Matrix Factorization. Clustering y clasificaci\u00f3n de textos: problemas y m\u00e9todos. An\u00e1lisis de sentimiento, afecto o subjetividad: Aplicaciones, herramientas, alcances y limitaciones. Lexicons, m\u00e9todos supervisados.",
    },
    position: {
      x: 1200,
      y: -1800,
    },
  },
  {
    id: "41",
    type: "custom",
    data: {
      codigo: "CD22",
      anio: 4,
      ciclo: null,
      cuatrimestre: 8,
      condicion: "electiva",
      materia: "Ciencia de Datos para las Finullzas",
      formato_didactico: "Asignatura",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD11",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones y desarrollos de ciencia de datos, estad\u00edstica, inform\u00e1tica y aprendizaje autom\u00e1tico espec\u00edficas para las finullzas.",
    },
    position: {
      x: -400,
      y: -2100,
    },
  },
  {
    id: "42",
    type: "custom",
    data: {
      codigo: "CD14",
      anio: 5,
      ciclo: null,
      cuatrimestre: 9,
      condicion: "electiva",
      materia: "Taller de An\u00e1lisis de Datos 2",
      formato_didactico: "Taller",
      ch_semanal: 8.0,
      ch_cuatrimestral: 128.0,
      creditos: 8.0,
      correlativas: "CD12",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        "Aplicaciones de algoritmos de an\u00e1lisis de datos y aprendizaje autom\u00e1ticos a problemas reales. Procesamiento de im\u00e1genes y video. Procesamiento del lenguaje natural. Finullzas y comercio.",
    },
    position: {
      x: 400,
      y: -2500,
    },
  },
  {
    id: "43",
    type: "custom",
    data: {
      codigo: "CD23",
      anio: 5,
      ciclo: null,
      cuatrimestre: 9,
      condicion: "electiva",
      materia: "Temas de Ciencias de la Computaci\u00f3n",
      formato_didactico: "Taller",
      ch_semanal: 6.0,
      ch_cuatrimestral: 96.0,
      creditos: 6.0,
      correlativas: "CD12",
      ch_presencial: null,
      ch_distancia: null,
      ch_total: null,
      descripcion:
        'Complejidad temporal y espacial de un algoritmo. T\u00e9cnicas algor\u00edtmicas. Algoritmos Recursivos. T\u00e9cnica "Divide & Conquer". Principio de Optimalidad y Programaci\u00f3n Din\u00e1mica. Backtracking y Branch and Bound. Algoritmos golosos. Repaso de teor\u00eda de grafos y aplicaciones. Algoritmos sobre grafos. Camino m\u00ednimo. \u00c1rboles generadores. Problemas de coloreo. Problema del viajante de comercio. Problema del flujo m\u00e1ximo. Problema del "Matching" en grafos. Introducci\u00f3n a la teor\u00eda de la complejidad. Clases P y NP. Reducciones Polinomiales. Clases NP-Hard y NP-Completo.',
    },
    position: {
      x: 600,
      y: -2500,
    },
  },
];

const initEdges: Edge[] = [
  {
    id: "e0-3",
    source: "0",
    target: "3",
  },
  {
    id: "e0-4",
    source: "0",
    target: "4",
  },
  {
    id: "e0-5",
    source: "0",
    target: "5",
  },
  {
    id: "e1-5",
    source: "1",
    target: "5",
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
  },
  {
    id: "e2-6",
    source: "2",
    target: "6",
  },
  {
    id: "e0-7",
    source: "0",
    target: "7",
  },
  {
    id: "e3-8",
    source: "3",
    target: "8",
  },
  {
    id: "e8-9",
    source: "8",
    target: "9",
  },
  {
    id: "e4-9",
    source: "4",
    target: "9",
  },
  {
    id: "e3-10",
    source: "3",
    target: "10",
  },
  {
    id: "e4-10",
    source: "4",
    target: "10",
  },
  {
    id: "e7-10",
    source: "7",
    target: "10",
  },
  {
    id: "e9-12",
    source: "9",
    target: "12",
  },
  {
    id: "e2-13",
    source: "2",
    target: "13",
  },
  {
    id: "e10-13",
    source: "10",
    target: "13",
  },
  {
    id: "e12-15",
    source: "12",
    target: "15",
  },
  {
    id: "e10-15",
    source: "10",
    target: "15",
  },
  {
    id: "e10-16",
    source: "10",
    target: "16",
  },
  {
    id: "e13-17",
    source: "13",
    target: "17",
  },
  {
    id: "e12-18",
    source: "12",
    target: "18",
  },
  {
    id: "e13-18",
    source: "13",
    target: "18",
  },
  {
    id: "e13-19",
    source: "13",
    target: "19",
  },
  {
    id: "e17-19",
    source: "17",
    target: "19",
  },
  {
    id: "e18-21",
    source: "18",
    target: "21",
  },
  {
    id: "e21-23",
    source: "21",
    target: "23",
  },
  {
    id: "e3-26",
    source: "3",
    target: "26",
  },
  {
    id: "e3-27",
    source: "3",
    target: "27",
  },
  {
    id: "e8-28",
    source: "8",
    target: "28",
  },
  {
    id: "e8-29",
    source: "8",
    target: "29",
  },
  {
    id: "e6-30",
    source: "6",
    target: "30",
  },
  {
    id: "e3-31",
    source: "3",
    target: "31",
  },
  {
    id: "e10-34",
    source: "10",
    target: "34",
  },
  {
    id: "e9-35",
    source: "9",
    target: "35",
  },
  {
    id: "e15-36",
    source: "15",
    target: "36",
  },
  {
    id: "e17-36",
    source: "17",
    target: "36",
  },
  {
    id: "e17-37",
    source: "17",
    target: "37",
  },
  {
    id: "e15-38",
    source: "15",
    target: "38",
  },
  {
    id: "e17-39",
    source: "17",
    target: "39",
  },
  {
    id: "e15-40",
    source: "15",
    target: "40",
  },
  {
    id: "e18-41",
    source: "18",
    target: "41",
  },
  {
    id: "e21-42",
    source: "21",
    target: "42",
  },
  {
    id: "e21-43",
    source: "21",
    target: "43",
  },
];

const CorrelativasTree = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState(initNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initEdges);

  const onConnect: OnConnect = useCallback(
    (connection) => setEdges((eds) => addEdge(connection, eds)),
    [setEdges]
  );

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      nodeTypes={nodeTypes}
      fitView
      className="bg-teal-50 min-h-[calc(100vh-64px)]"
    >
      <MiniMap />
      <Controls />
    </ReactFlow>
  );
};

export default CorrelativasTree;
